; !(import! &self agents)

; !((create-agent ./agents/mettaAgents/AFImportanceDiffusionAgent.metta) (g 3))
; !((create-agent ./agents/mettaAgents/WAImportanceDiffusionAgent.metta) (g 3))

; !((create-agent ./agents/mettaAgents/AFRentCollectionAgent.metta) (g 3))
; !((create-agent ./agents/mettaAgents/WARentCollectionAgent.metta) (g 3))

; !((create-agent ./agents/mettaAgents/ForgettingAgent.metta) (g 3))
; !((create-agent ./agents/mettaAgents/HebbianCreationAgent.metta) (g 3))
; !((create-agent ./agents/mettaAgents/HebbianUpdatingAgent.metta) (g 3))
