!(register-module! ../../../../../../metta-attention)
!(import! &self metta-attention:attention-bank:utilities:helper-functions)
!(import! &self metta-attention:attention-bank:attention-value:getter-and-setter)
!(import! &self metta-attention:attention-bank:bank:atom-bins:atombins)
!(import! &self metta-attention:attention-bank:bank:attention-bank)
!(import! &self metta-attention:attention-bank:bank:attentional-focus:attentional-focus)
!(import! &self metta-attention:attention-bank:bank:importance-index:importance-index)
!(import! &self metta-attention:attention-bank:utilities:recentVal)
!(import! &self metta-attention:attention:agents::HebbianCreationAgent:hebbianCreationagent)mettaAgents


!(getAfMaxSTI)
!(setAv a (0.0 0.0 0.0))
!(setAv d (7.0 4.0 0.0))
!(setAv c (0.0 0.0 0.0))

!(setAv a (0.0 0.0 0.0))
!(setAv d (7.0 4.0 0.0))
!(setAv c (0.0 0.0 0.0))
!(setAv A (100.0 200.0 300.0))
!(setAv B (50.0 150.0 250.0))
!(setAv C (200.0 300.0 400.0))
!(setAv D (25.0 125.0 225.0))
!(setAv F (70.0 100.0 200.0))
!(setAv G (300.0 400.0 500.0))
!(setAv H (15.0 20.0 35.0))
!(setAv I (500.0 600.0 700.0))


; !(addLink (Abebe Kebede) )
; !(getAtomList)

!(hello)

!(addAtomToAFCustom a)
!(addAtomToAFCustom A)
!(addAtomToAFCustom B)
!(addAtomToAFCustom C)
!(addAtomToAFCustom D)
!(addAtomToAFCustom F)
!(addAtomToAFCustom G)
!(addAtomToAFCustom H)
!(addAtomToAFCustom I)

!(getAtomList)
a
